### ISSUE TITLE
 Extract release notes (exit code: 1) 

### ISSUE THREAD

**Issue by OlegGordiichuk** [bitrise-io/steps-script#11]
Recently I start to receive this kind of error.

+------------------------------------------------------------------------------+

| (6) Extract release notes                                                    |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-01-22T02:53:47-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
FATA[10:53:49] [ENVMAN] - Failed to read file value: open ./releasenotes/.txt: no such file or directory 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Extract release notes (exit code: 1)                          | 3.53 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Hi @OlegGordiichuk ,

This is not an issue with this step. This step just runs the script you set for it to execute.

From the error it seems you have an `envman add` command there, specifying a file parameter, but the file does not exist at the given path (which seems to be `./releasenotes/.txt`).

Please double check that the file exists there. Based on the "strange" file name I'd say you probably specified the txt file's name with an Env Var, but that env var is not set (that's why it's just `.txt` instead of something like `abc.txt`).

I'll close this issue here as it's not an issue with the step, but feel free to ask any questions or share the script **content** and we'll try to help as much as we can :)

**Comment by OlegGordiichuk** [comment]
@viktorbenei this step randomly crash build.

**Comment by viktorbenei** [comment]
It's not the step, it's the script you specified in the step. The step fails because your script fails. Your script fails because you specify a path in the script which does not exist. The step can't do anything else other than to fail, as the file does not exist there :)
