### ISSUE TITLE
Groups with Spaces in name not working

### ISSUE THREAD

**Issue by hanshamm** [bitrise-io/steps-script#16]
When I setup Groups as follows:
`envman add --key APPCENTER_GROUPS --value "ONE GROUP,Another Group"`

it wont work. The command is failing with 400:

`Committing the release
  result is 200: {"release_id":"1234","release_url":"v0.1/apps/company/app-name/releases/1234"}
  distribution groups are ONE GROUP Another Group
Adding to distribution group ONE
API call failed with 400: {"release_notes":"develop/pipelinetest - Test Build Pipeline XXY regular app - please ignore","code":"bad_request","message":"Distribution Group with id undefined does not exist."}
`

I suppose the command should have used quotes?

**Comment by bitce** [comment]
Hi @hanshamm!

I’m really sorry about the delay in getting to your issue. We are currently migrating to a new system in order to be able to assist you better in the future. Due to the considerable delay please let us know if your issue still requires investigation; please send us a short message and also attach a relevant build's URL.

 Again, apologies for the delay, going forward we’ll do our best to offer quicker replies. Thanks!
